name: Camlin Backend Engineer Test - CI

on:
  push:
    branches: [master]

env:
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  JWT_ALGORITHM: ${{ secrets.JWT_ALGORITHM }}
  EXCHANGE_URL: ${{ secrets.EXCHANGE_URL }}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13']

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install .

      - name: Run tests
        run: pytest
      
      - name: Build Docker image
        run: docker build -t JakeWalker23/camlin-backend-test:latest .
