name: Camlin Backend Engineer Test - CI

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13']

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install .

      - name: Format code with Black
        run: black --check .

      - name: Lint code with flake8
        run: flake8 .

      - name: Run tests
        run: pytest
      
      - name: Build Docker image
        run: docker build -t yourusername/yourapp:latest .
